### ISSUE TITLE
divrem. warning

### ISSUE THREAD

**Issue by alexhallam** [alexhallam/Stemplot.jl#2]
Since converting to Julia 0.6 `divrem.` will give a warning. This will not effect the functionality, it is just an annoyance. 

[#22119](https://github.com/JuliaLang/julia/issues/22119#issuecomment-305019185)

**Comment by equinetic** [comment]
This should be fixed in the PR, the warning was because it was being passed arrays - broadcasting with dot notation avoids the warning.

**Comment by alexhallam** [comment]
Great, thanks for working on that.
